### ISSUE TITLE
SMA Module import errors out

### ISSUE THREAD

**Issue by qb411** [raandree/NTFSSecurity#18]
Hi there, 

We decided to use your module to try and setup automation within our SMA platform.  Unfortunately when we import the module it generates an error as follows:

>8/31/2017 11:20:40 AM, Verbose: 93e025b2-f06c-420c-8fb7-a23b6b346168:[localhost]:Dot-sourcing the script file 
>'C:\Users\SMA\Documents\WindowsPowerShell\Modules\NTFSSecurity\NTFSSecurity.Init.ps1'.

-------------------------------------

> 8/31/2017 11:20:40 AM, Error: Update-FormatData : Updating format data is not allowed in this runspace. The 'DisableFormatUpdates' property is set to 
True when creating the runspace.
At AUD_Homedir:16 char:16
>+ 
 >   + CategoryInfo          : InvalidOperation: (:) [Update-FormatData], PSInvalidOperationException
  >  + FullyQualifiedErrorId : >InvalidOperation,Microsoft.PowerShell.Commands.UpdateFormatDataCommand

It appears to be a problem with the init script.  I'm taking a look at this, but it seems to be a common issue with the SMA platform.   Another module programmer has experienced this issue:
https://github.com/KirkMunro/ScsmPx/issues/2 

I've queried to find out what he did to work around this issue.   However if you have any input, I'd appreciate any ideas on how we can fix the issue.

**Comment by qb411** [comment]
So I've found a workaround for this problem with SMA. 

[System.Management.Automation.Runspaces.Runspace]::DefaultRunspace.InitialSessionState.DisableFormatUpdates = $false
            Import-Module NTFSSecurity -ErrorAction SilentlyContinue
            [System.Management.Automation.Runspaces.Runspace]::DefaultRunspace.InitialSessionState.DisableFormatUpdates = $true 

You can include the DisableFormatUpdates flag on the runspace to load the module.   This is purely a workaround, and based on what KirkMunro replied with, it sounds like we need to refactor the way the NTFSSecurity module is creating its data view. 

Will continue to update, but its a workaround for now.

**Comment by raandree** [comment]
Merged, thanks!
