### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by SignFinder** [raandree/NTFSSecurity#29]
Hi team,
Could you kindly give us info about possibility to update library using the last version AlphaFS and the possibility to use it with new PS  versions.

**Comment by nyanhp** [comment]
Hi @SignFinder , updating to the latest AlphaFS should be no problem, but it won't be compatible with .NET Core and PowerShell Core if that is what you mean. AlphaFS does not target .NET core or .NET standard as far as I can see. I am not sure if our own code would support this without modifications

**Comment by SignFinder** [comment]
Thanks for your answer.
I suppose that the good idea to update alphafs in this repo, because the repo with last update after two year looks as dead project.

**Comment by raandree** [comment]
@nyanhp, you had an idea of how to integrate AlphaFS is a better way. Are you thinking about using it as a submodule?

**Comment by nyanhp** [comment]
@raandree I have put in a pull request that adds alpha as a nuget package. Unless you intend to make changes to the alpha code this ensures we always use the currently available version.any changes to the alpha code should be made there and once they are in production our build grabs them automatically

**Comment by raandree** [comment]
Perfect idea and merged.
