### ISSUE TITLE
Backup / restore ownership/permissions of the whole drive recursively?

### ISSUE THREAD

**Issue by gsustek** [raandree/NTFSSecurity#31]
Hi, if i want to fix ownership and permissions off whole drive recursively and i have good and bad snapshot of them. What commands should would it be?
something like:

owneship:
PS C:\> dir -Recurse | Get-NTFSOwner | Export-Csv C:\ownership.csv
##### in favorite editor replace C: with G: in C:\ownership.csv
PS G:\> Import-Csv C:\ownership.csv | Set-NTFSOwner - doesn't work

permissions:
PS C:\> dir -Recurse | Get-NTFSAccess -ExcludeInherited | Export-Csv C:\permissions.csv
##### in favorite editor replace C: with G: in C:\permissions.csv
PS G:\> Import-Csv C:\permissions.csv | Add-NTFSAccess - doesn't work

and what about using privileges ? backup restore roles...maybe through that account;
Thank you..

**Comment by raandree** [comment]
If a direct pipe to the cmdlet does not work, you can always use it in a ForEach loop and bind the parameters yourself.

The account you want to use is wither a backup operator or administrator.
