### ISSUE TITLE
Expand group members in output

### ISSUE THREAD

**Issue by valentijnscholten** [raandree/NTFSSecurity#38]
Hi,

I suggest to (optionally) expand the groups in the output and (resursively) show their members.

Use-case:

On our fileserver all permissions are assigned to AD groups, which are then managed by the servicedesk.
The current output only shows group names. This makes sense, because these are in the ACL on the filesystem.

As a reviewer of permissions I would be helped if the output (optionally) could expand all the groups and list their members with their permissions.

This would allow me to generate one report with all information in it. This will make reviewing it a lot faster. It will also help the different "folder owners" to review the permissions on their folder when I share that section of the report with them.

I have been googling/searching for this, but I can't seem to find an existing solution.

Valentijn

**Comment by raandree** [comment]
Hi and thanks for the feature request.

I would like to keep the module as focused as possible. Adding functions for reporting do not really fit into the scope.

There may not be a ready solution for this but I am sure the are snippets that you can combine with NTFSSecurity to get this report.
