### ISSUE TITLE
Get-NTFSAccess bug in Method ToSimpleFileSystemAccessRule2()

### ISSUE THREAD

**Issue by ZamElek** [raandree/NTFSSecurity#48]
Steps to reproduce: 
- Set deny ACE on folder
- Get object Security2.FileSystemAccessRule2 using Get-NTFSAccess
- Call method ToSimpleFileSystemAccessRule2() on objects which Type is "Deny"
- The method returns Security2.SimpleFileSystemAccessRule object with wrong property Type="Allow", but should be "Deny"

**Comment by raandree** [comment]
Thanks for reporting this. Will be fixes in the next release this week.
