### ISSUE TITLE
"Authenticated users" Question

### ISSUE THREAD

**Issue by johancop** [raandree/NTFSSecurity#51]
Hello,

First thanks for the NTFSecurity module.
A small question, Is it always necessary to remove inheritance from files and folders before one can remove-access from internal OS groups like for example the "Authenticated users"? And if you need to remove inheritance, do you enable inheritance again after the changes has been made?

As example.
FolderA - on creation it has "Administrators","System","Users" and Authenticated users",, the problem is that Authenticated users" have modify permission, I want to remove these permission, but am only able when I disable inheritance?

Hope you can explain more what would be the best way. This is on windows 10 OS.
thanks in advance.
johan

**Comment by mwtrigg** [comment]
That is how NTFS works, you can't modify inherited permissions without first disabling inheritance - else, that would kind of defeat the purpose of inheritance. You can add additional entries (ACEs) if desired. you reenable inheritance after the change, you're just going to get the same permissions back again.  Another option would be to look at the parent directory (or wherever the permissions originate) andbmodify the inheritable permissions at that point.

This question (if further clarification is required) would probably be better suited for a general technical forum, as it does not specifically pertain to this project, module, or functionality, rather the behavior of the underlying file system against which this module operates.

Just my thoughts as an appreciative follower of the project.

**Comment by johancop** [comment]
Thanks for the info and clarification
