### ISSUE TITLE
NTFSSecurity v4.2.4 fails on Import-Module in PowerShell 2.0

### ISSUE THREAD

**Issue by Regen379** [raandree/NTFSSecurity#53]
https://www.powershellgallery.com/packages/NTFSSecurity/4.2.4 says Minimum PowerShell version = 2.0, but "Import-Module NTFSSecurity" fails for v4.2.4 in PowerShell 2.0 (Windows 7 x64). Works ok in PowerShell 3.0 (.Net Framework 4.0).

`Add-Type : Could not load file or assembly 'file:///C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\Sec
urity2.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and
 cannot be loaded.
At C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\NTFSSecurity.Init.ps1:75 char:9
+ Add-Type <<<<  -Path $PSScriptRoot\Security2.dll
    + CategoryInfo          : NotSpecified: (:) [Add-Type], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Could not load file or assembly 'file:///C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\Pri
vilegeControl.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runt
ime and cannot be loaded.
At C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\NTFSSecurity.Init.ps1:76 char:9
+ Add-Type <<<<  -Path $PSScriptRoot\PrivilegeControl.dll -ReferencedAssemblies $PSScriptRoot\ProcessPrivileges.dll
    + CategoryInfo          : NotSpecified: (:) [Add-Type], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Could not load file or assembly 'file:///C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\Pro
cessPrivileges.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded run
time and cannot be loaded.
At C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurity\NTFSSecurity.Init.ps1:77 char:9
+ Add-Type <<<<  -Path $PSScriptRoot\ProcessPrivileges.dll
    + CategoryInfo          : NotSpecified: (:) [Add-Type], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.AddTypeCommand

Import-Module : Could not load file or assembly 'file:///C:\Users\Username\Documents\WindowsPowerShell\Modules\NTFSSecurit
y\NTFSSecurity.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded run
time and cannot be loaded.
At line:1 char:14
+ import-module <<<<  NTFSSecurity
    + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand
`

**Comment by raandree** [comment]
Right, since version 4.2.4 NTFSSecurity is compiled with .net 4.0 which works out-of-the-box on all 2012+ systems. For older operating systems, please try version [4.2.3](https://github.com/raandree/NTFSSecurity/releases/tag/4.2.3). The older version is also available in the gallery.

**Comment by Regen379** [comment]
Is there any reason this can't be compiled with the older version of .Net so that it supports PowerShell 2.0? https://www.powershellgallery.com/packages/NTFSSecurity/4.2.4 says Minimum PowerShell version = 2.0. It would be good to continue support for PowerShell 2.0 as my client still has more than 200 Win2008R2 servers. At the time that v4.2.4 was released (Aug 2018) there was still more than a year of support for Win2008R2 left. I'm not the only person trying to run this on Win2008R2, please see the questions "Runtime version" and "Run on 2008 R2?" in the Q and A at https://gallery.technet.microsoft.com/scriptcenter/1abd77a5-9c0b-4a2b-acef-90dbb2b84e85/view/Discussions#content

The version notes at https://gallery.technet.microsoft.com/scriptcenter/1abd77a5-9c0b-4a2b-acef-90dbb2b84e85 list "Added Cmdlet Get-FileHash2" for both v4.2.3 and v4.2.4. Is this accurate or a copy&paste error? What features or bug fixes am I missing out on by using v4.2.3?
