### ISSUE TITLE
How to remove sids

### ISSUE THREAD

**Issue by bvi1998** [raandree/NTFSSecurity#55]
Hi, I am finishing up a file server migration with permissions and need to delete the local account sid which came from the other server. 
Thanks for this module, it's fantastic! It saves me so much time ;)
Thanks!

**Comment by raandree** [comment]
Do you mean removing a SID from the ACL that can no longer be resovled?

**Comment by bvi1998** [comment]
Yes, thanks!

**Comment by raandree** [comment]
That's quite easy then:

```powershell
Get-NTFSOrphanedAccess | Remove-NTFSAccess
```

**Comment by bvi1998** [comment]
Oh my gosh sorry I didn’t see that command available. At least someone might find this question if they are searching for the same thing. Thanks for all of your work this module is fantastic.
