### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by ajacks88** [raandree/NTFSSecurity#6]
Downloaded NTFSSecurity-master.zip today, "unblocked" the files in the permissions tab, extracted zipped folder, created "NTFSSecurity" folder within C:\Windows\System32\WindowsPowerShell\v1.0\Modules, copied all files extracted from the zipped folder into the NTFSSecurity folder, launched PowerShell x64 as admin, ran "Import-Module NTFSSecurity" and i get the following error: import-module : The specified module 'ntfssecurity' was not loaded because no valid module file was found in any module directory. I replicated this issue on another machine following the same steps. This is running Windows 10 with PowerShell 5.

**Comment by raandree** [comment]
The zip file you have downloaded is the source code and not the compiled module. Please download it from [](https://github.com/raandree/NTFSSecurity/releases/tag/4.2.3).
