### ISSUE TITLE
readme hyperlinks

### ISSUE THREAD

**Issue by shawnwat** [raandree/NTFSSecurity#65]
The new location of the MS tutorials are:
https://docs.microsoft.com/en-us/archive/blogs/fieldcoding/ntfssecurity-tutorial-2-managing-ntfs-inheritance-and-using-privileges
https://docs.microsoft.com/en-us/archive/blogs/fieldcoding/ntfssecurity-tutorial-1-getting-adding-and-removing-permissions

**Comment by raandree** [comment]
Thanks, will correct this.
