### ISSUE TITLE
Add a switch to point at specific dcs

### ISSUE THREAD

**Issue by PGomersall** [raandree/NTFSSecurity#75]
It would be really nice if you could add a switch to the cmdlets that may use an ad user or group so that a specific domain controller could be specified. Much like may of the AD cmdlets with -Server

**Comment by Sup3rlativ3** [comment]
What would be the use case for this? I would expect that every DC should be the same in the domain. I would also expect that sites are configured correctly in AD so that the best DC is hit.

**Comment by PGomersall** [comment]
For example you have complex script that may need to run silently and with say looping, you use in it:
1) new-aduser $newusername -Server $DC (can take multiple seconds to replicate to each dc in a large domain). In testing in our domain this can take up to 30 seconds.
2) New-Item \\$computername\D$\newfolder -ItemType Directory
3) Add-NTFSAccess \\$computername\D$\newfolder -Account $newusername etc. This step can fail, if the lookup for the account hits a dc without the user created in step 1 yet.
Now obviously I can have a try catch block to check each dc in turn and wait until the account is replicated to all dcs, but it would be useful if the NTFSSecurity cmdlets had the ability to specify the dc for a lookup.
In fact this exact request has been made other times in the QA where the module was originally posted: https://gallery.technet.microsoft.com/1abd77a5-9c0b-4a2b-acef-90dbb2b84e85/view/Discussions/15 "Specify DC" in 2015.

**Comment by raandree** [comment]
Sorry, @PGomersall, this is not possible. I am not using the AD cmdlets or LDAP to do the name resolution but an extended version of the built-in classes ```S.S.P.NTAccount``` and ```S.S.P.SecurityDescriptor```. The code is in the class [IdentityReference2](https://github.com/raandree/NTFSSecurity/blob/master/Security2/IdentityReference2.cs).

The translate method of an ```IdentityReference``` does not provide a parameter to specify the domain controller that should be used. This is all handled somewhere in the OS.

```
PS D:\> $s = New-Object System.Security.Principal.NTAccount('randr')

PS D:\> $s.Translate

OverloadDefinitions                                                     
-------------------                                                     
System.Security.Principal.IdentityReference Translate(type targetType)  
                                                                        



PS D:\> $s.Translate([System.Security.Principal.SecurityIdentifier])

BinaryLength AccountDomainSid                          Value                                         
------------ ----------------                          -----                                         
          28 S-1-5-21-4218060545-2912297629-1072315737 S-1-5-21-4218060545-2912297629-1072315737-1003
```

**Comment by PGomersall** [comment]
Thanks for the input.
